-- Food History Phase 1 backend migrations
-- PostgreSQL reference profile. Run files in lexical order.
-- UUIDv7 values are generated by the application/import layer, not by PostgreSQL.

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE SCHEMA IF NOT EXISTS food_history;
SET search_path TO food_history, public;


CREATE TABLE "schema_version" (
    "schema_version_id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    "version" varchar(32) NOT NULL UNIQUE,
    "applied_at" timestamptz NOT NULL DEFAULT now(),
    "description" text,
    CONSTRAINT "pk_schema_version_" PRIMARY KEY ("schema_version_id")
);
COMMENT ON TABLE "schema_version" IS 'Tracks database/schema releases independently from taxonomy releases.';

CREATE TABLE "app_user" (
    "user_id" uuid NOT NULL,
    "display_name" text NOT NULL,
    "email_normalized" text UNIQUE,
    "is_staff" boolean NOT NULL DEFAULT false,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "pk_app_user_" PRIMARY KEY ("user_id")
);
COMMENT ON TABLE "app_user" IS 'Authentication-independent application user identity for audit trails and editorial workflow.';
