SET search_path TO food_history, public;

-- Foreign keys
ALTER TABLE "taxonomy_term" ADD CONSTRAINT "fk_taxonomy_term_vocabulary_id" FOREIGN KEY ("vocabulary_id") REFERENCES "vocabulary" ("vocabulary_id") ON DELETE RESTRICT;
ALTER TABLE "taxonomy_term" ADD CONSTRAINT "fk_taxonomy_term_replaced_by_term_id" FOREIGN KEY ("replaced_by_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "taxonomy_label" ADD CONSTRAINT "fk_taxonomy_label_term_id" FOREIGN KEY ("term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE CASCADE;
ALTER TABLE "taxonomy_edge" ADD CONSTRAINT "fk_taxonomy_edge_child_term_id" FOREIGN KEY ("child_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE CASCADE;
ALTER TABLE "taxonomy_edge" ADD CONSTRAINT "fk_taxonomy_edge_parent_term_id" FOREIGN KEY ("parent_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE CASCADE;
ALTER TABLE "taxonomy_mapping" ADD CONSTRAINT "fk_taxonomy_mapping_term_id" FOREIGN KEY ("term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE CASCADE;
ALTER TABLE "taxonomy_mapping" ADD CONSTRAINT "fk_taxonomy_mapping_confidence_term_id" FOREIGN KEY ("confidence_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "entity" ADD CONSTRAINT "fk_entity_entity_type_term_id" FOREIGN KEY ("entity_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "entity" ADD CONSTRAINT "fk_entity_merged_into_entity_id" FOREIGN KEY ("merged_into_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "entity" ADD CONSTRAINT "fk_entity_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "app_user" ("user_id") ON DELETE SET NULL;
ALTER TABLE "entity" ADD CONSTRAINT "fk_entity_updated_by_user_id" FOREIGN KEY ("updated_by_user_id") REFERENCES "app_user" ("user_id") ON DELETE SET NULL;
ALTER TABLE "entity_name" ADD CONSTRAINT "fk_entity_name_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "entity_note" ADD CONSTRAINT "fk_entity_note_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "entity_note" ADD CONSTRAINT "fk_entity_note_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "app_user" ("user_id") ON DELETE SET NULL;
ALTER TABLE "external_identifier" ADD CONSTRAINT "fk_external_identifier_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "entity_language" ADD CONSTRAINT "fk_entity_language_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "entity_term_assignment" ADD CONSTRAINT "fk_entity_term_assignment_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "entity_term_assignment" ADD CONSTRAINT "fk_entity_term_assignment_term_id" FOREIGN KEY ("term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "entity_term_assignment" ADD CONSTRAINT "fk_entity_term_assignment_confidence_term_id" FOREIGN KEY ("confidence_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "citation" ADD CONSTRAINT "fk_citation_source_entity_id" FOREIGN KEY ("source_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "citation" ADD CONSTRAINT "fk_citation_repository_entity_id" FOREIGN KEY ("repository_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "entity_name" ADD CONSTRAINT "fk_entity_name_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "external_identifier" ADD CONSTRAINT "fk_external_identifier_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "entity_term_assignment" ADD CONSTRAINT "fk_entity_term_assignment_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_subject_entity_id" FOREIGN KEY ("subject_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_predicate_term_id" FOREIGN KEY ("predicate_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_object_entity_id" FOREIGN KEY ("object_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_unit_entity_id" FOREIGN KEY ("unit_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_qualifier_place_entity_id" FOREIGN KEY ("qualifier_place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_claim_status_term_id" FOREIGN KEY ("claim_status_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_confidence_term_id" FOREIGN KEY ("confidence_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "assertion" ADD CONSTRAINT "fk_assertion_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "app_user" ("user_id") ON DELETE SET NULL;
ALTER TABLE "assertion_evidence" ADD CONSTRAINT "fk_assertion_evidence_assertion_id" FOREIGN KEY ("assertion_id") REFERENCES "assertion" ("assertion_id") ON DELETE CASCADE;
ALTER TABLE "assertion_evidence" ADD CONSTRAINT "fk_assertion_evidence_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE CASCADE;
ALTER TABLE "assertion_evidence" ADD CONSTRAINT "fk_assertion_evidence_strength_term_id" FOREIGN KEY ("strength_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "observation" ADD CONSTRAINT "fk_observation_observation_entity_id" FOREIGN KEY ("observation_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "observation" ADD CONSTRAINT "fk_observation_observed_entity_id" FOREIGN KEY ("observed_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "observation" ADD CONSTRAINT "fk_observation_observation_type_term_id" FOREIGN KEY ("observation_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "observation" ADD CONSTRAINT "fk_observation_source_entity_id" FOREIGN KEY ("source_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "observation" ADD CONSTRAINT "fk_observation_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "observation" ADD CONSTRAINT "fk_observation_place_entity_id" FOREIGN KEY ("place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "observation" ADD CONSTRAINT "fk_observation_confidence_term_id" FOREIGN KEY ("confidence_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "person" ADD CONSTRAINT "fk_person_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "organization" ADD CONSTRAINT "fk_organization_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "organization" ADD CONSTRAINT "fk_organization_organization_type_term_id" FOREIGN KEY ("organization_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "place" ADD CONSTRAINT "fk_place_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "place" ADD CONSTRAINT "fk_place_place_type_term_id" FOREIGN KEY ("place_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "place" ADD CONSTRAINT "fk_place_parent_place_entity_id" FOREIGN KEY ("parent_place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "place_address" ADD CONSTRAINT "fk_place_address_place_entity_id" FOREIGN KEY ("place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "place_address" ADD CONSTRAINT "fk_place_address_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "event" ADD CONSTRAINT "fk_event_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "event" ADD CONSTRAINT "fk_event_event_type_term_id" FOREIGN KEY ("event_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "event" ADD CONSTRAINT "fk_event_place_entity_id" FOREIGN KEY ("place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "culinary_concept" ADD CONSTRAINT "fk_culinary_concept_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "culinary_concept" ADD CONSTRAINT "fk_culinary_concept_concept_type_term_id" FOREIGN KEY ("concept_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "recipe" ADD CONSTRAINT "fk_recipe_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "recipe" ADD CONSTRAINT "fk_recipe_recipe_type_term_id" FOREIGN KEY ("recipe_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "recipe_occurrence" ADD CONSTRAINT "fk_recipe_occurrence_recipe_entity_id" FOREIGN KEY ("recipe_entity_id") REFERENCES "recipe" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "recipe_occurrence" ADD CONSTRAINT "fk_recipe_occurrence_source_entity_id" FOREIGN KEY ("source_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "recipe_occurrence" ADD CONSTRAINT "fk_recipe_occurrence_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "recipe_occurrence" ADD CONSTRAINT "fk_recipe_occurrence_transcription_id" FOREIGN KEY ("transcription_id") REFERENCES "transcription" ("transcription_id") ON DELETE SET NULL;
ALTER TABLE "recipe_occurrence" ADD CONSTRAINT "fk_recipe_occurrence_confidence_term_id" FOREIGN KEY ("confidence_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "brand" ADD CONSTRAINT "fk_brand_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "product" ADD CONSTRAINT "fk_product_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "product" ADD CONSTRAINT "fk_product_generic_food_entity_id" FOREIGN KEY ("generic_food_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "product_brand_assignment" ADD CONSTRAINT "fk_product_brand_assignment_product_entity_id" FOREIGN KEY ("product_entity_id") REFERENCES "product" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "product_brand_assignment" ADD CONSTRAINT "fk_product_brand_assignment_brand_entity_id" FOREIGN KEY ("brand_entity_id") REFERENCES "brand" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "product_brand_assignment" ADD CONSTRAINT "fk_product_brand_assignment_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "work" ADD CONSTRAINT "fk_work_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "work" ADD CONSTRAINT "fk_work_work_type_term_id" FOREIGN KEY ("work_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "expression" ADD CONSTRAINT "fk_expression_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "expression" ADD CONSTRAINT "fk_expression_work_entity_id" FOREIGN KEY ("work_entity_id") REFERENCES "work" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "manifestation" ADD CONSTRAINT "fk_manifestation_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "manifestation_expression" ADD CONSTRAINT "fk_manifestation_expression_manifestation_entity_id" FOREIGN KEY ("manifestation_entity_id") REFERENCES "manifestation" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "manifestation_expression" ADD CONSTRAINT "fk_manifestation_expression_expression_entity_id" FOREIGN KEY ("expression_entity_id") REFERENCES "expression" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "item" ADD CONSTRAINT "fk_item_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "item" ADD CONSTRAINT "fk_item_manifestation_entity_id" FOREIGN KEY ("manifestation_entity_id") REFERENCES "manifestation" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "credit" ADD CONSTRAINT "fk_credit_resource_entity_id" FOREIGN KEY ("resource_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "credit" ADD CONSTRAINT "fk_credit_agent_entity_id" FOREIGN KEY ("agent_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "credit" ADD CONSTRAINT "fk_credit_role_term_id" FOREIGN KEY ("role_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "credit" ADD CONSTRAINT "fk_credit_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "publication_statement" ADD CONSTRAINT "fk_publication_statement_manifestation_entity_id" FOREIGN KEY ("manifestation_entity_id") REFERENCES "manifestation" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "publication_statement" ADD CONSTRAINT "fk_publication_statement_agent_entity_id" FOREIGN KEY ("agent_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "publication_statement" ADD CONSTRAINT "fk_publication_statement_place_entity_id" FOREIGN KEY ("place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "document" ADD CONSTRAINT "fk_document_entity_id" FOREIGN KEY ("entity_id") REFERENCES "item" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "document" ADD CONSTRAINT "fk_document_document_type_term_id" FOREIGN KEY ("document_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "menu" ADD CONSTRAINT "fk_menu_entity_id" FOREIGN KEY ("entity_id") REFERENCES "document" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "menu" ADD CONSTRAINT "fk_menu_menu_type_term_id" FOREIGN KEY ("menu_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "menu" ADD CONSTRAINT "fk_menu_establishment_entity_id" FOREIGN KEY ("establishment_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "menu" ADD CONSTRAINT "fk_menu_host_event_entity_id" FOREIGN KEY ("host_event_entity_id") REFERENCES "event" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "menu" ADD CONSTRAINT "fk_menu_meal_term_id" FOREIGN KEY ("meal_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "menu_section" ADD CONSTRAINT "fk_menu_section_menu_entity_id" FOREIGN KEY ("menu_entity_id") REFERENCES "menu" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "menu_section" ADD CONSTRAINT "fk_menu_section_course_term_id" FOREIGN KEY ("course_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "menu_item" ADD CONSTRAINT "fk_menu_item_menu_entity_id" FOREIGN KEY ("menu_entity_id") REFERENCES "menu" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "menu_item" ADD CONSTRAINT "fk_menu_item_menu_section_id" FOREIGN KEY ("menu_section_id") REFERENCES "menu_section" ("menu_section_id") ON DELETE SET NULL;
ALTER TABLE "menu_item" ADD CONSTRAINT "fk_menu_item_normalized_food_entity_id" FOREIGN KEY ("normalized_food_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "menu_item" ADD CONSTRAINT "fk_menu_item_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "digital_resource" ADD CONSTRAINT "fk_digital_resource_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "digital_resource" ADD CONSTRAINT "fk_digital_resource_resource_type_term_id" FOREIGN KEY ("resource_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "digital_resource" ADD CONSTRAINT "fk_digital_resource_source_digital_entity_id" FOREIGN KEY ("source_digital_entity_id") REFERENCES "digital_resource" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "digital_representation" ADD CONSTRAINT "fk_digital_representation_digital_entity_id" FOREIGN KEY ("digital_entity_id") REFERENCES "digital_resource" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "digital_representation" ADD CONSTRAINT "fk_digital_representation_represented_entity_id" FOREIGN KEY ("represented_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "transcription" ADD CONSTRAINT "fk_transcription_source_entity_id" FOREIGN KEY ("source_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "transcription" ADD CONSTRAINT "fk_transcription_digital_entity_id" FOREIGN KEY ("digital_entity_id") REFERENCES "digital_resource" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "transcription" ADD CONSTRAINT "fk_transcription_reviewed_by_user_id" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "app_user" ("user_id") ON DELETE SET NULL;
ALTER TABLE "physical_object" ADD CONSTRAINT "fk_physical_object_entity_id" FOREIGN KEY ("entity_id") REFERENCES "item" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "physical_object" ADD CONSTRAINT "fk_physical_object_object_type_term_id" FOREIGN KEY ("object_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE RESTRICT;
ALTER TABLE "measurement" ADD CONSTRAINT "fk_measurement_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "object_mark" ADD CONSTRAINT "fk_object_mark_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "object_mark" ADD CONSTRAINT "fk_object_mark_maker_entity_id" FOREIGN KEY ("maker_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "object_mark" ADD CONSTRAINT "fk_object_mark_digital_entity_id" FOREIGN KEY ("digital_entity_id") REFERENCES "digital_resource" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "object_mark" ADD CONSTRAINT "fk_object_mark_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "production_record" ADD CONSTRAINT "fk_production_record_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "production_record" ADD CONSTRAINT "fk_production_record_manufacturer_entity_id" FOREIGN KEY ("manufacturer_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "production_record" ADD CONSTRAINT "fk_production_record_production_place_entity_id" FOREIGN KEY ("production_place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "production_record" ADD CONSTRAINT "fk_production_record_process_term_id" FOREIGN KEY ("process_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "production_record" ADD CONSTRAINT "fk_production_record_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "condition_assessment" ADD CONSTRAINT "fk_condition_assessment_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "condition_assessment" ADD CONSTRAINT "fk_condition_assessment_condition_term_id" FOREIGN KEY ("condition_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "condition_assessment" ADD CONSTRAINT "fk_condition_assessment_assessor_entity_id" FOREIGN KEY ("assessor_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "condition_assessment" ADD CONSTRAINT "fk_condition_assessment_assessor_user_id" FOREIGN KEY ("assessor_user_id") REFERENCES "app_user" ("user_id") ON DELETE SET NULL;
ALTER TABLE "condition_assessment" ADD CONSTRAINT "fk_condition_assessment_digital_entity_id" FOREIGN KEY ("digital_entity_id") REFERENCES "digital_resource" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "collection" ADD CONSTRAINT "fk_collection_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "collection" ADD CONSTRAINT "fk_collection_collection_type_term_id" FOREIGN KEY ("collection_type_term_id") REFERENCES "taxonomy_term" ("term_id") ON DELETE SET NULL;
ALTER TABLE "collection" ADD CONSTRAINT "fk_collection_owning_entity_id" FOREIGN KEY ("owning_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "collection_membership" ADD CONSTRAINT "fk_collection_membership_collection_entity_id" FOREIGN KEY ("collection_entity_id") REFERENCES "collection" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "collection_membership" ADD CONSTRAINT "fk_collection_membership_member_entity_id" FOREIGN KEY ("member_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "collection_membership" ADD CONSTRAINT "fk_collection_membership_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "holding" ADD CONSTRAINT "fk_holding_item_entity_id" FOREIGN KEY ("item_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "holding" ADD CONSTRAINT "fk_holding_holder_entity_id" FOREIGN KEY ("holder_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "holding" ADD CONSTRAINT "fk_holding_collection_entity_id" FOREIGN KEY ("collection_entity_id") REFERENCES "collection" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "holding" ADD CONSTRAINT "fk_holding_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "provenance_event" ADD CONSTRAINT "fk_provenance_event_subject_entity_id" FOREIGN KEY ("subject_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "provenance_event" ADD CONSTRAINT "fk_provenance_event_from_entity_id" FOREIGN KEY ("from_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "provenance_event" ADD CONSTRAINT "fk_provenance_event_to_entity_id" FOREIGN KEY ("to_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "provenance_event" ADD CONSTRAINT "fk_provenance_event_place_entity_id" FOREIGN KEY ("place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "provenance_event" ADD CONSTRAINT "fk_provenance_event_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "price_observation" ADD CONSTRAINT "fk_price_observation_subject_entity_id" FOREIGN KEY ("subject_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "price_observation" ADD CONSTRAINT "fk_price_observation_place_entity_id" FOREIGN KEY ("place_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "price_observation" ADD CONSTRAINT "fk_price_observation_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE RESTRICT;
ALTER TABLE "transaction_event" ADD CONSTRAINT "fk_transaction_event_entity_id" FOREIGN KEY ("entity_id") REFERENCES "event" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "transaction_event" ADD CONSTRAINT "fk_transaction_event_seller_entity_id" FOREIGN KEY ("seller_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "transaction_event" ADD CONSTRAINT "fk_transaction_event_buyer_entity_id" FOREIGN KEY ("buyer_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "transaction_event" ADD CONSTRAINT "fk_transaction_event_venue_entity_id" FOREIGN KEY ("venue_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "transaction_event" ADD CONSTRAINT "fk_transaction_event_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "provenance_event" ADD CONSTRAINT "fk_provenance_event_transaction_entity_id" FOREIGN KEY ("transaction_entity_id") REFERENCES "transaction_event" ("entity_id") ON DELETE SET NULL;
ALTER TABLE "transaction_line" ADD CONSTRAINT "fk_transaction_line_transaction_entity_id" FOREIGN KEY ("transaction_entity_id") REFERENCES "transaction_event" ("entity_id") ON DELETE CASCADE;
ALTER TABLE "transaction_line" ADD CONSTRAINT "fk_transaction_line_subject_entity_id" FOREIGN KEY ("subject_entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "transaction_line" ADD CONSTRAINT "fk_transaction_line_citation_id" FOREIGN KEY ("citation_id") REFERENCES "citation" ("citation_id") ON DELETE SET NULL;
ALTER TABLE "rights_assignment" ADD CONSTRAINT "fk_rights_assignment_entity_id" FOREIGN KEY ("entity_id") REFERENCES "entity" ("entity_id") ON DELETE RESTRICT;
ALTER TABLE "rights_assignment" ADD CONSTRAINT "fk_rights_assignment_rights_holder_entity_id" FOREIGN KEY ("rights_holder_entity_id") REFERENCES "entity" ("entity_id") ON DELETE SET NULL;

-- Business/uniqueness constraints
ALTER TABLE "taxonomy_edge" ADD CONSTRAINT "uq_taxonomy_edge" UNIQUE (child_term_id, parent_term_id, edge_type);
ALTER TABLE "taxonomy_label" ADD CONSTRAINT "uq_taxonomy_label" UNIQUE (term_id, label_type, language_tag, label_text);
ALTER TABLE "external_identifier" ADD CONSTRAINT "uq_external_identifier" UNIQUE (scheme_code, identifier_value);
ALTER TABLE "assertion" ADD CONSTRAINT "ck_assertion_value" CHECK (((value_kind='entity') AND object_entity_id IS NOT NULL) OR ((value_kind='text') AND value_text IS NOT NULL) OR ((value_kind='number') AND value_number IS NOT NULL) OR ((value_kind='date') AND value_date IS NOT NULL) OR ((value_kind='boolean') AND value_boolean IS NOT NULL) OR ((value_kind='json') AND value_json IS NOT NULL));
ALTER TABLE "menu_section" ADD CONSTRAINT "uq_menu_section_sequence" UNIQUE (menu_entity_id, sequence);
ALTER TABLE "menu_item" ADD CONSTRAINT "uq_menu_item_sequence" UNIQUE (menu_entity_id, sequence);
ALTER TABLE "manifestation_expression" ADD CONSTRAINT "uq_manifestation_expression" UNIQUE (manifestation_entity_id, expression_entity_id);
ALTER TABLE "collection_membership" ADD CONSTRAINT "uq_collection_member" UNIQUE (collection_entity_id, member_entity_id, membership_role);
CREATE UNIQUE INDEX "uq_current_holding" ON "holding" (item_entity_id) WHERE is_current = true;
CREATE UNIQUE INDEX "uq_digital_resource_sha256" ON "digital_resource" (sha256) WHERE sha256 IS NOT NULL;
ALTER TABLE "menu_item" ADD CONSTRAINT "ck_menu_item_transcription_confidence" CHECK (transcription_confidence IS NULL OR (transcription_confidence >= 0 AND transcription_confidence <= 1));
ALTER TABLE "transcription" ADD CONSTRAINT "ck_transcription_overall_confidence" CHECK (overall_confidence IS NULL OR (overall_confidence >= 0 AND overall_confidence <= 1));
